services:
  zenoh:
    image: eclipse/zenoh:latest
    container_name: zenoh
    ports:
      - "7447:7447"
    networks:
      - kuksa

  databroker:
    image: ghcr.io/eclipse-kuksa/kuksa-databroker:latest
    container_name: databroker
    command: ["--insecure", "--vss", "/app/vss.json"]
    volumes:
      - type: bind
        source: ./vss.json
        target: /app/vss.json
        read_only: true
    ports:
      - "30000:55555"
    networks:
      - kuksa

  databroker-cli:
    image: ghcr.io/eclipse-kuksa/kuksa-databroker-cli:main
    container_name: databroker-cli
    depends_on:
      - databroker
    command:
      - "--server"
      - "databroker:55555"
    stdin_open: true
    tty: true
    networks:
      - kuksa

  can-provider:
    image: ghcr.io/eclipse-kuksa/kuksa-can-provider/can-provider
    container_name: can-provider
    depends_on:
      - databroker
    volumes:
      - type: bind
        source: ./config/dbc_feeder.ini
        target: /config/dbc_feeder.ini
        read_only: true
      - type: bind
        source: ./Model3CAN.dbc
        target: /mapping/Model3CAN.dbc
        read_only: true
      - type: bind
        source: ./mapping/vss_dbc.json
        target: /mapping/vss_dbc.json
        read_only: true
      - type: bind
        source: ./candump-2021-12-08_151848.log
        target: /data/candump-2021-12-08_151848.log
        read_only: true
    command: ["--config", "/config/dbc_feeder.ini"]
    networks:
      - kuksa


  subscriber:
    build:
      context: .
      dockerfile: Dockerfile
      target: subscriber
    container_name: subscriber
    depends_on:
      - zenoh
    environment:
      - RUST_LOG=debug,zenoh=debug
    networks:
      - kuksa

  publisher:
    build:
      context: .
      dockerfile: Dockerfile
      target: publisher
    container_name: publisher
    depends_on:
      - zenoh
    environment:
      - RUST_LOG=debug,zenoh=debug
    networks:
      - kuksa

  provider:
    build:
      context: .
      dockerfile: Dockerfile
      target: provider
    container_name: provider
    depends_on:
      - zenoh
      - databroker
    environment:
      - RUST_LOG=info,zenoh=debug,RUST_BACKTRACE=1
    networks:
      - kuksa


networks:
  kuksa:
    driver: bridge